#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
     CREATE USER $POSTGRES_WEB_USER WITH PASSWORD '$POSTGRES_WEB_PASS'; 
     GRANT SELECT, INSERT ON cve TO $POSTGRES_WEB_USER;
     GRANT USAGE, SELECT ON SEQUENCE cve_id_seq TO $POSTGRES_WEB_USER;          
EOSQL